# -*- coding: utf-8 -*-
"""AIML_ML_Project_full_code_notebook_sindhuja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCjY3ZN8YhIWo1sTrC63b3dcIKE4Q2JZ

## Problem Statement

### Context

AllLife Bank is a US bank that has a growing customer base. The majority of these customers are liability customers (depositors) with varying sizes of deposits. The number of customers who are also borrowers (asset customers) is quite small, and the bank is interested in expanding this base rapidly to bring in more loan business and in the process, earn more through the interest on loans. In particular, the management wants to explore ways of converting its liability customers to personal loan customers (while retaining them as depositors).

A campaign that the bank ran last year for liability customers showed a healthy conversion rate of over 9% success. This has encouraged the retail marketing department to devise campaigns with better target marketing to increase the success ratio.

You as a Data scientist at AllLife bank have to build a model that will help the marketing department to identify the potential customers who have a higher probability of purchasing the loan.

### Objective

To predict whether a liability customer will buy personal loans, to understand which customer attributes are most significant in driving purchases, and identify which segment of customers to target more.

### Data Dictionary
* `ID`: Customer ID
* `Age`: Customer’s age in completed years
* `Experience`: #years of professional experience
* `Income`: Annual income of the customer (in thousand dollars)
* `ZIP Code`: Home Address ZIP code.
* `Family`: the Family size of the customer
* `CCAvg`: Average spending on credit cards per month (in thousand dollars)
* `Education`: Education Level. 1: Undergrad; 2: Graduate;3: Advanced/Professional
* `Mortgage`: Value of house mortgage if any. (in thousand dollars)
* `Personal_Loan`: Did this customer accept the personal loan offered in the last campaign? (0: No, 1: Yes)
* `Securities_Account`: Does the customer have securities account with the bank? (0: No, 1: Yes)
* `CD_Account`: Does the customer have a certificate of deposit (CD) account with the bank? (0: No, 1: Yes)
* `Online`: Do customers use internet banking facilities? (0: No, 1: Yes)
* `CreditCard`: Does the customer use a credit card issued by any other Bank (excluding All life Bank)? (0: No, 1: Yes)

## Importing necessary libraries
"""

# Installing the libraries with the specified version.
!pip install numpy==1.25.2 pandas==1.5.3 matplotlib==3.7.1 seaborn==0.13.1 scikit-learn==1.2.2 sklearn-pandas==2.2.0 -q --user

"""**Note**:

1. After running the above cell, kindly restart the notebook kernel (for Jupyter Notebook) or runtime (for Google Colab), write the relevant code for the project from the next cell, and run all cells sequentially from the next cell.

2. On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in this notebook.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Loading the dataset"""

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/content/Loan_Modelling.csv')
df_org_1=df.copy()
df_org_2=df.copy()

"""## Data Overview

* Observations
* Sanity checks
"""

df.shape

"""This dataset has 5000 rows and 14 columns"""

df.info()

df.head(5)

"""The datatype for all features in these dataset are numeric

## Exploratory Data Analysis.
"""

df.describe().T

"""- EDA is an important part of any project involving data.
- It is important to investigate and understand the data better before building a model with it.
- A few questions have been mentioned below which will help you approach the analysis in the right manner and generate insights from the data.
- A thorough analysis of the data, in addition to the questions mentioned below, should be done.

**Questions**:

1. What is the distribution of mortgage attribute? Are there any noticeable patterns or outliers in the distribution?
2. How many customers have credit cards?
3. What are the attributes that have a strong correlation with the target attribute (personal loan)?
4. How does a customer's interest in purchasing a loan vary with their age?
5. How does a customer's interest in purchasing a loan vary with their education?
"""

sns.histplot(data=df,x='Age')
sns.boxplot(data=df,x='Age')

"""Feature - Age

Normally distributed & No outliers
"""

sns.histplot(data=df,x='Experience')
sns.boxplot(data=df,x='Experience')

"""Feature - Experience

Normally distributed & No outliers
"""

sns.histplot(data=df,x='Income')
sns.boxplot(data=df,x='Income')

"""Feature - Income

rightly skewed & it has outliers

most of the data points falls under lower end (~40 to 65)
"""

sns.histplot(data=df,x='ZIPCode')
sns.boxplot(data=df,x='ZIPCode')

"""Feature - Zipcode

Normally distributed & No outliers
"""

sns.histplot(data=df,x='Family')
sns.boxplot(data=df,x='Family')

"""Feature - Experience

Normally distributed & range from 1 to 3
"""

sns.histplot(data=df,x='CCAvg')
sns.boxplot(data=df,x='CCAvg')

"""Feature - CCAvg

Right skewed & it has outliers
"""

sns.countplot(data=df,x='Education')

"""Customer couunt is more for the Undergrad degress (~2200)"""

sns.histplot(data=df,x='Mortgage')
sns.boxplot(data=df,x='Mortgage')

sns.countplot(data=df,x='Personal_Loan')

"""Give more priority to minor class "Personal load acceped in last campaign (1)". Give Class weights for this minority data."""

sns.countplot(data=df,x='Securities_Account')

sns.countplot(data=df,x='CD_Account')

sns.countplot(data=df,x='Online')

sns.countplot(data=df,x='CreditCard')

df.describe().T

corr = df.corr(numeric_only = True)

# plot the heatmap
sns.heatmap(corr,  annot=True, vmin=-1, vmax=1, fmt=".2f", cmap="Spectral")

sns.boxplot(x=df['Personal_Loan'], y=df['Age'])

sns.boxplot(x=df['Personal_Loan'], y=df['Income'])

sns.boxplot(x=df['Personal_Loan'], y=df['Education'])

sns.boxplot(x=df['Personal_Loan'], y=df['CCAvg'])

"""1. What is the distribution of mortgage attribute? Are there any noticeable patterns or outliers in the distribution?

mean = 56.50
median = 0

mean > median

Positively skewed

Most of the data points are concentrated in lower end 0- 100k

2. How many customers have credit cards?
Around 1400 customers has credit card out of 5000 customers

3. What are the attributes that have a strong correlation with the target attribute (personal loan)?

Target Attribute has strong correlation with below attributes in specific order

i) Income (0.50)
ii) CCAvg (0.37)
iii) CD_Account (0.32)


4. How does a customer's interest in purchasing a loan vary with their age?

From the boxplot, it is not showing any srong relationship between customer's interest in purchasing a loan with their age

5. How does a customer's interest in purchasing a loan vary with their education?

From the box plot, It shows customer's with education 2 & above (Graduate & Advanced) getting more personal loan

## Data Preprocessing

* Missing value treatment
* Feature engineering (if needed)
* Outlier detection and treatment (if needed)
* Preparing data for modeling
* Any other preprocessing steps (if needed)
"""

df.isnull().sum()

"""There are no missing values in the dataset

"""

df.duplicated().sum()

"""
There are no duplicate values in the dataset
"""

df.ID.nunique()

"""This ID feature has unique data & we can drop it

"""

df=df.drop('ID',axis=1)

# Assign input & output
X = df.drop('Personal_Loan', axis=1)
Y = df['Personal_Loan']

#split data in train & test (30 % for test & 70% for train)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

print("Shape of Training set : ", X_train.shape)
print("Shape of test set : ", X_test.shape)
print("Percentage of classes in training set:")
print(Y_train.value_counts(normalize=True))
print("Percentage of classes in test set:")
print(Y_test.value_counts(normalize=True))

"""This shows 90.5% of data belongs to customer who doesn't opt for personal load & ~9.4 % of data belongs to customer who opt for personal loan in train & test data

## Model Building

### Model Evaluation Criterion

Model can make wrong prediction as:
1. Predicting a customer who take personal loan but in reality, the customer won't take personal loan (FP)
2. Predicting a customer who won't take personal loan but in reality, the customer take personal loan (FN)

Whic case is more important?

Eventhough both the cases are important, recall should be maximized (by decreasing FN)
"""

#defining a function to compute different metrics to check performance of a classification model built using sklearn
def model_performance_classification_sklearn(model, predictors, target):
    """
    Function to compute different metrics to check classification model performance

    model: classifier
    predictors: independent variables
    target: dependent variable
    """

    # predicting using the independent variables
    pred = model.predict(predictors)

    acc = accuracy_score(target, pred)  # to compute Accuracy
    recall = recall_score(target, pred)  # to compute Recall
    precision = precision_score(target, pred)  # to compute Precision
    f1 = f1_score(target, pred)  # to compute F1-score

    # creating a dataframe of metrics
    df_perf = pd.DataFrame(
        {"Accuracy": acc, "Recall": recall, "Precision": precision, "F1": f1,},
        index=[0],
    )

    return df_perf

def confusion_matrix_sklearn(model, predictors, target):
    """
    To plot the confusion_matrix with percentages

    model: classifier
    predictors: independent variables
    target: dependent variable
    """
    y_pred = model.predict(predictors)
    cm = confusion_matrix(target, y_pred)
    labels = np.asarray(
        [
            ["{0:0.0f}".format(item) + "\n{0:.2%}".format(item / cm.flatten().sum())]
            for item in cm.flatten()
        ]
    ).reshape(2, 2)

    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=labels, fmt="")
    plt.ylabel("True label")
    plt.xlabel("Predicted label")

# Base model (model 0)
# Decision Tree(default) Fully grown tree

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

# To build model for prediction
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

model0= DecisionTreeClassifier(random_state=1)
model0.fit(X_train, Y_train)

confusion_matrix_sklearn(model0, X_train, Y_train)

decision_tree_default_perf_train = model_performance_classification_sklearn(
    model0, X_train, Y_train
)
decision_tree_default_perf_train

"""Train data set performance shows the model is Overfit

Lets check the performance in test data set
"""

confusion_matrix_sklearn(model0, X_test, Y_test)

decision_tree_default_perf_test = model_performance_classification_sklearn(
    model0, X_test, Y_test
)
decision_tree_default_perf_test

"""Acuuracy & Recall & Precision & F1 score dropped from 1 in test data set when compared to train dara set performance. So it looks overfitting."""

# Lets check other model to reduce overfitting

# Base model (model 1 with class_weights)
# Decision tree (fully grown tree)

model1 = DecisionTreeClassifier(random_state=1, class_weight="balanced")
# With class weight, giving more priority to minority group (customer who opt for personal_loan)
model1.fit(X_train, Y_train)

confusion_matrix_sklearn(model1, X_train, Y_train)

decision_tree_perf_train = model_performance_classification_sklearn(
    model1, X_train, Y_train
)
decision_tree_perf_train

"""It looks overfitting as same as model0"""

confusion_matrix_sklearn(model1, X_test, Y_test)

decision_tree_perf_test = model_performance_classification_sklearn(
    model1, X_test, Y_test
)
decision_tree_perf_test

"""Accuracy & Recall & Precision & F1 score reduced in test data performance when compared to train data performance. So this model is also considered as overfitting

### Model Building
"""

# Model 2 (Decision tree with Prepruning)

# Define the parameters of the tree to iterate over
max_depth_values = np.arange(2, 9, 2) # 2 4 6 8
max_leaf_nodes_values = [50, 75, 150, 250]
min_samples_split_values = [10, 30, 50, 70]

# This gives 64 combinations
# find the tree which gives highest recall

# Initialize variables to store the best model and its performance
best_estimator = None
best_score_diff = float('inf')
best_test_score = 0.0

# Iterate over all combinations of the specified parameter values
for max_depth in max_depth_values:
    for max_leaf_nodes in max_leaf_nodes_values:
        for min_samples_split in min_samples_split_values:

            # Initialize the tree with the current set of parameters
            estimator = DecisionTreeClassifier(
                max_depth=max_depth,
                max_leaf_nodes=max_leaf_nodes,
                min_samples_split=min_samples_split,
                class_weight='balanced',
                random_state=42
            )

            # Fit the model to the training data
            estimator.fit(X_train, Y_train)

            # Make predictions on the training and test sets
            y_train_pred = estimator.predict(X_train)
            y_test_pred = estimator.predict(X_test)

            # Calculate recall scores for training and test sets
            train_recall_score = recall_score(Y_train, y_train_pred)
            test_recall_score = recall_score(Y_test, y_test_pred)

            # Calculate the absolute difference between training and test recall scores (objective - min)
            score_diff = abs(train_recall_score - test_recall_score)

            # Update the best estimator and best score if the current one has a smaller score difference
            if (score_diff < best_score_diff) & (test_recall_score > best_test_score):
                best_score_diff = score_diff
                best_test_score = test_recall_score
                best_estimator = estimator

# Print the best parameters
print("Best parameters found:")
print(f"Max depth: {best_estimator.max_depth}")
print(f"Max leaf nodes: {best_estimator.max_leaf_nodes}")
print(f"Min samples split: {best_estimator.min_samples_split}")
print(f"Best test recall score: {best_test_score}")

model2 = best_estimator

model2.fit(X_train, Y_train)

confusion_matrix_sklearn(model2, X_train, Y_train)

decision_tree_tune_perf_train = model_performance_classification_sklearn(
    model2, X_train, Y_train
)
decision_tree_tune_perf_train

confusion_matrix_sklearn(model2, X_test, Y_test)

decision_tree_tune_perf_test = model_performance_classification_sklearn(
    model2, X_test, Y_test
)
decision_tree_tune_perf_test

"""Recall in Test & Train data shows 1 with Model2 (Decision tree with prepruning)"""

feature_names = list(X_train.columns)
importances = model2.feature_importances_
indices = np.argsort(importances)

plt.figure(figsize=(20, 10))
out = tree.plot_tree(
    model2,
    feature_names=feature_names,
    filled=True,
    fontsize=9,
    node_ids=False,
    class_names=None,
)
# below code will add arrows to the decision tree split if they are missing
for o in out:
    arrow = o.arrow_patch
    if arrow is not None:
        arrow.set_edgecolor("black")
        arrow.set_linewidth(1)
plt.show()

"""This tree shows not all leaf nodes are pure since gini index is != 0 for all leaf nodes. So this is not overfitting"""

# Text report showing the rules of a decision tree -
print(tree.export_text(model2, feature_names=feature_names, show_weights=True))

importances = model2.feature_importances_
importances

importances = model2.feature_importances_
indices = np.argsort(importances)

plt.figure(figsize=(8, 8))
plt.title("Feature Importances")
plt.barh(range(len(indices)), importances[indices], color="violet", align="center")
plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
plt.xlabel("Relative Importance")
plt.show()

"""Important feature in model2 (decision tree with prepruning) is "Income" to predict the customer who will take personal_load"""

# Model 3 (Decision tree with post pruning)

clf = DecisionTreeClassifier(random_state=1, class_weight="balanced")
path = clf.cost_complexity_pruning_path(X_train, Y_train)
ccp_alphas, impurities = abs(path.ccp_alphas), path.impurities

pd.DataFrame(path)

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(ccp_alphas[:-1], impurities[:-1], marker="o", drawstyle="steps-post")
ax.set_xlabel("effective alpha")
ax.set_ylabel("total impurity of leaves")
ax.set_title("Total Impurity vs effective alpha for training set")
plt.show()

clfs = []
for ccp_alpha in ccp_alphas:
    clf = DecisionTreeClassifier(
        random_state=1, ccp_alpha=ccp_alpha, class_weight="balanced"
    )
    clf.fit(X_train, Y_train)
    clfs.append(clf)
print(
    "Number of nodes in the last tree is: {} with ccp_alpha: {}".format(
        clfs[-1].tree_.node_count, ccp_alphas[-1]
    )
)

clfs = clfs[:-1]
ccp_alphas = ccp_alphas[:-1]

node_counts = [clf.tree_.node_count for clf in clfs]
depth = [clf.tree_.max_depth for clf in clfs]
fig, ax = plt.subplots(2, 1, figsize=(10, 7))
ax[0].plot(ccp_alphas, node_counts, marker="o", drawstyle="steps-post")
ax[0].set_xlabel("alpha")
ax[0].set_ylabel("number of nodes")
ax[0].set_title("Number of nodes vs alpha")
ax[1].plot(ccp_alphas, depth, marker="o", drawstyle="steps-post")
ax[1].set_xlabel("alpha")
ax[1].set_ylabel("depth of tree")
ax[1].set_title("Depth vs alpha")
fig.tight_layout()

recall_train = []
for clf in clfs:
    pred_train = clf.predict(X_train)
    values_train = recall_score(Y_train, pred_train)
    recall_train.append(values_train)

recall_test = []
for clf in clfs:
    pred_test = clf.predict(X_test)
    values_test = recall_score(Y_test, pred_test)
    recall_test.append(values_test)

train_scores = [clf.score(X_train, Y_train) for clf in clfs]
test_scores = [clf.score(X_test, Y_test) for clf in clfs]

fig, ax = plt.subplots(figsize=(15, 5))
ax.set_xlabel("alpha")
ax.set_ylabel("Recall")
ax.set_title("Recall vs alpha for training and testing sets")
ax.plot(
    ccp_alphas, recall_train, marker="o", label="train", drawstyle="steps-post",
)
ax.plot(ccp_alphas, recall_test, marker="o", label="test", drawstyle="steps-post")
ax.legend()
plt.show()

"""When recall 1 , alpha 0 -> overfitting
Post pruning

base point (train vs test) - 0.99 (recall) 0.01 (ccp alpha)
"""

# creating the model where we get highest train and test recall
index_best_model = np.argmax(recall_test)
best_model = clfs[index_best_model]
print(best_model)

model3 = best_model
confusion_matrix_sklearn(model3, X_train, Y_train)

decision_tree_post_perf_train = model_performance_classification_sklearn(
    model3, X_train, Y_train
)
decision_tree_post_perf_train

confusion_matrix_sklearn(model3, X_test, Y_test)

decision_tree_post_test = model_performance_classification_sklearn(
    model3, X_test, Y_test
)
decision_tree_post_test

plt.figure(figsize=(20, 10))

out = tree.plot_tree(
    model3,
    feature_names=feature_names,
    filled=True,
    fontsize=9,
    node_ids=False,
    class_names=None,
)
for o in out:
    arrow = o.arrow_patch
    if arrow is not None:
        arrow.set_edgecolor("black")
        arrow.set_linewidth(1)
plt.show()

# Text report showing the rules of a decision tree -

print(tree.export_text(model3, feature_names=feature_names, show_weights=True))

importances = model3.feature_importances_
indices = np.argsort(importances)

plt.figure(figsize=(12, 12))
plt.title("Feature Importances")
plt.barh(range(len(indices)), importances[indices], color="violet", align="center")
plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
plt.xlabel("Relative Importance")
plt.show()

"""Important feature in post pruning model is "Income"

## Model Performance Improvement
"""



"""## Model Performance Comparison and Final Model Selection"""

models_train_comp_df = pd.concat(
    [
        decision_tree_default_perf_train.T,
        decision_tree_perf_train.T,
        decision_tree_tune_perf_train.T,
        decision_tree_post_perf_train.T,
    ],
    axis=1,
)
models_train_comp_df.columns = [
    "Decision Tree (sklearn default)",
    "Decision Tree with class_weight",
    "Decision Tree (Pre-Pruning)",
    "Decision Tree (Post-Pruning)",
]
print("Training performance comparison:")
models_train_comp_df

models_test_comp_df = pd.concat(
    [
        decision_tree_default_perf_test.T,
        decision_tree_perf_test.T,
        decision_tree_tune_perf_test.T,
        decision_tree_post_test.T,
    ],
    axis=1,
)
models_test_comp_df.columns = [
    "Decision Tree (sklearn default)",
    "Decision Tree with class_weight",
    "Decision Tree (Pre-Pruning)",
    "Decision Tree (Post-Pruning)",
]
print("Test set performance comparison:")
models_test_comp_df

"""1.   Decision tree model with Prepruning gives high recall in both train & test data set
2.   We are choosing the pre-pruning model for this case study

## Actionable Insights and Business Recommendations

:* What recommedations would you suggest to the bank?



*  This model (decision tree with prepruning model2) is used to predict whether a liability customers who will buy personal loans

*   The feature "Income" plays a major role in predicting the liability customers who will buy personal loans. So marketing team can first contact to customers who has more income.

*   Marketing team can contact higher education customers who are more likely to avail personal loan

*   Marketing team can contact customers who are paying credit card average spending likely to avail personal loan

___
"""