# -*- coding: utf-8 -*-
"""Learner_Notebook_Full_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-wXWWkfnecSp6Fs-5_fF1YmDOGU7NeS

# Project Python Foundations: FoodHub Data Analysis

### Context

The number of restaurants in New York is increasing day by day. Lots of students and busy professionals rely on those restaurants due to their hectic lifestyles. Online food delivery service is a great option for them. It provides them with good food from their favorite restaurants. A food aggregator company FoodHub offers access to multiple restaurants through a single smartphone app.

The app allows the restaurants to receive a direct online order from a customer. The app assigns a delivery person from the company to pick up the order after it is confirmed by the restaurant. The delivery person then uses the map to reach the restaurant and waits for the food package. Once the food package is handed over to the delivery person, he/she confirms the pick-up in the app and travels to the customer's location to deliver the food. The delivery person confirms the drop-off in the app after delivering the food package to the customer. The customer can rate the order in the app. The food aggregator earns money by collecting a fixed margin of the delivery order from the restaurants.

### Objective

The food aggregator company has stored the data of the different orders made by the registered customers in their online portal. They want to analyze the data to get a fair idea about the demand of different restaurants which will help them in enhancing their customer experience. Suppose you are hired as a Data Scientist in this company and the Data Science team has shared some of the key questions that need to be answered. Perform the data analysis to find answers to these questions that will help the company to improve the business.

### Data Description

The data contains the different data related to a food order. The detailed data dictionary is given below.

### Data Dictionary

* order_id: Unique ID of the order
* customer_id: ID of the customer who ordered the food
* restaurant_name: Name of the restaurant
* cuisine_type: Cuisine ordered by the customer
* cost_of_the_order: Cost of the order
* day_of_the_week: Indicates whether the order is placed on a weekday or weekend (The weekday is from Monday to Friday and the weekend is Saturday and Sunday)
* rating: Rating given by the customer out of 5
* food_preparation_time: Time (in minutes) taken by the restaurant to prepare the food. This is calculated by taking the difference between the timestamps of the restaurant's order confirmation and the delivery person's pick-up confirmation.
* delivery_time: Time (in minutes) taken by the delivery person to deliver the food package. This is calculated by taking the difference between the timestamps of the delivery person's pick-up confirmation and drop-off information

### Let us start by importing the required libraries
"""

# Installing the libraries with the specified version.
!pip install numpy==1.25.2 pandas==1.5.3 matplotlib==3.7.1 seaborn==0.13.1 -q --user

from google.colab import drive
drive.mount('/content/drive')

"""**Note**: *After running the above cell, kindly restart the notebook kernel and run all cells sequentially from the start again.*"""

# import libraries for data manipulation
import numpy as np
import pandas as pd

# import libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

"""### Understanding the structure of the data"""

# uncomment and run the following lines for Google Colab
from google.colab import drive
drive.mount('/content/drive')

# Write your code here to read the data
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/content/foodhub_order.csv')
df_multi=df.copy()
df_2 = df.copy()

# Write your code here to view the first 5 rows
df.head()

"""### **Question 1:** How many rows and columns are present in the data? [0.5 mark]"""

# Write your code here
df.shape

"""#### Observations:
This dataset has 1898 rows and 9 columns

### **Question 2:** What are the datatypes of the different columns in the dataset? (The info() function can be used) [0.5 mark]
"""

# Write your code here
df.info()

# Changed object data types to numerical data type
df['restaurant_name'] = df['restaurant_name'].astype('string')
df['cuisine_type'] = df['cuisine_type'].astype('string')
df['rating'] = pd.to_numeric(df['rating'],errors='coerce')
df.info()

"""#### Observations:
1. All columns has 1898 observations. So there is no missing values
2. These columns has data type as object - "restaurant_name", "cuisine_type", "day_of_the_week","rating" & other columns are numerical type
3. Converted Object data types to String (or) Numerical data type

### **Question 3:** Are there any missing values in the data? If yes, treat them using an appropriate method. [1 mark]
"""

# Write your code here
df.isnull().sum()

"""#### Observations:
There are no missing values in the dataset

### **Question 4:** Check the statistical summary of the data. What is the minimum, average, and maximum time it takes for food to be prepared once an order is placed? [2 marks]
"""

# Write your code here
df.describe().T

print('minimum time for food to be prepared', df['food_preparation_time'].min(), 'minutes')
print('averate time for food to be prepared', int(df['food_preparation_time'].mean()), 'minutes')
print('maximum time for food to be prepared', df['food_preparation_time'].max(), 'minutes')

"""#### Observations:
The statistical summary of the time takes for food to be prepared
minimum = 20 minutes,
Average (mean) = 	2.737197e+01 minutes (or) 27.37197 minutes (or) 27 minutes,
maximun = 35 minutes

### **Question 5:** How many orders are not rated? [1 mark]
"""

# Write the code here
df_2['rating'].value_counts(normalize=True)

"""#### Observations:
There are 39% of orders are not rated

0.39×1898=740.22
There are 740 orders are not rated out of 1898 orders

### Exploratory Data Analysis (EDA)

### Univariate Analysis

### **Question 6:** Explore all the variables and provide observations on their distributions. (Generally, histograms, boxplots, countplots, etc. are used for univariate exploration.) [9 marks]
"""

# Write the code here

# order_id
df['order_id'].nunique()
# order id is unique for each observation, since order id matched with total rows count

# customer_id
df['customer_id'].nunique()
# customer id is not unique for each observation
df['customer_id'].value_counts()
# Customer id 52832 ordered more time (~13) than other customers

# restuarant_name
df['restaurant_name'].nunique()
# restuarant_name is not unique for each observation
# Since this is categorical data, using count plot
plt.figure(figsize = (20,5))
sns.countplot(data=df, x='restaurant_name')

# cuisine_type
df['cuisine_type'].nunique()
print(df['cuisine_type'].value_counts())
# cuisine_type is not unique for each observation
# Since this is categorical data, using count plot
plt.figure(figsize = (20,5))
sns.countplot(data=df, x='cuisine_type')

# There are more american cuisine in the data set

# cost_of_the_order
df['cost_of_the_order'].nunique()
print(df['cost_of_the_order'].value_counts())
# cost_of_the_order is not unique for each observation
# Since this is numerical data, using historical & box plot
sns.histplot(data=df,x='cost_of_the_order')
plt.show()
# There are more oreders in the range 10 to 15

sns.boxplot(data=df,x='cost_of_the_order')
plt.show()
# Median is closer to Q1. Most of the orders concentrated in lower end

# day_of_the_week
df['day_of_the_week'].nunique()
print(df['day_of_the_week'].value_counts())
# day_of_the_week is not unique for each observation
# Since this is categorical data, using count plot
sns.countplot(data=df, x='day_of_the_week')

# It shows weekend has more no of orders when compared to weekday

# rating
df['rating'].nunique()
print(df['rating'].value_counts())
# rating is not unique for each observation
# Since this is categorical data, using count plot
sns.countplot(data=df, x='rating')

# Most of the orders (~700) are not rated

# food_preparation_time
df['food_preparation_time'].nunique()
# food_preparation_time is not unique for each observation
# Since this is numerical data, using historical & box plot

sns.histplot(data=df,x='food_preparation_time')
plt.show()
# More no of orders has food preparation time between 20 to 21 minutes

sns.boxplot(data=df,x='food_preparation_time')
plt.show()
# median is at the center, so data is normally distributed

# delivery_time
df['delivery_time'].nunique()
# delivery_time is not unique for each observation
# Since this is numerical data, using historical & box plot
sns.histplot(data=df,x='delivery_time')
plt.show()
# Most of the orders has delivery time between 27.5 minutes to 30 minutes

sns.boxplot(data=df,x='delivery_time')
plt.show()
# left skewed
# most of the delivery_time data points are concentrated in the higher end

"""### **Question 7**: Which are the top 5 restaurants in terms of the number of orders received? [1 mark]"""

# Write the code here
df['restaurant_name'].value_counts().head()

"""#### Observations:

1. Shake Shack has most no of orders in the data set - 219
2. Second restaurant for more no of orders in the data set - 132
3. third restaurant for more no of orders in the data set - 119
4. fourth restaurant for more no of orders in the data set - 96
5. fifth restaurant for more no of orders in the data set - 68

### **Question 8**: Which is the most popular cuisine on weekends? [1 mark]
"""

# Write the code here
# Filter weekend rows
df_day = df[df['day_of_the_week'] == 'Weekend']
# Count the no of cuisine
df_day['cuisine_type'].value_counts().idxmax()

"""#### Observations:
The most popular cuisine on weekend is 'American'

### **Question 9**: What percentage of the orders cost more than 20 dollars? [2 marks]
"""

# Write the code here
# Filter rows with cost > 20
df_more_than_20 = df[df['cost_of_the_order'] > 20]
df_more_than_20_count = df_more_than_20.shape[0]
df_more_than_20_per = (df_more_than_20.shape[0] / df.shape[0]) * 100
print(round(df_more_than_20_per, 0),'%')

"""#### Observations:
There are 29% of the orders has cost more than 20 dollars

### **Question 10**: What is the mean order delivery time? [1 mark]
"""

# Write the code here
del_time_mean = df['delivery_time'].mean()
print(round(del_time_mean, 0),'minutes')

"""#### Observations:
The average order delivery time is 24 minutes

### **Question 11:** The company has decided to give 20% discount vouchers to the top 3 most frequent customers. Find the IDs of these customers and the number of orders they placed. [1 mark]
"""

# Write the code here
df['customer_id'].value_counts().head(3)

"""#### Observations:
The below customers get 20% discount vouchers
1. Customer ID 52832 ordered food 13 times
2. Customer ID 47440 ordered food 10 times
3. Customer ID 83287 ordered food 9 times

### Multivariate Analysis

### **Question 12**: Perform a multivariate analysis to explore relationships between the important variables in the dataset. (It is a good idea to explore relations between numerical variables as well as relations between numerical and categorical variables) [10 marks]
"""

# Write the code here
# heatmap
# select numerical variables
df_multi.drop('order_id', axis=1, inplace=True)
df_multi.drop('customer_id', axis=1, inplace=True)
num_var = df_multi.dtypes[df_multi.dtypes != 'object'].index

corr = df_multi[num_var].corr(numeric_only = True)

# plot the heatmap
sns.heatmap(corr,  annot=True, vmin=-1, vmax=1, fmt=".2f", cmap="Spectral")

# Observation:
# It is not showing any strong correlation

# Scatter plot
sns.pairplot(data=df_multi[num_var], diag_kind="kde")
plt.show()

# Observation
# It is not showing any strong relationship between data points

# Numerical vs Categorical
# Categorical - cuisine_type
plt.figure(figsize=(15,7))
sns.boxplot(x=df['cuisine_type'], y=df['cost_of_the_order'])

# Observation
# It shows Southern cuisine has more cost of the order

# Numerical vs Categorical
plt.figure(figsize=(15,8))
sns.boxplot(x=df['cuisine_type'], y=df['food_preparation_time'])

# Numerical vs Categorical
plt.figure(figsize=(15,8))
sns.boxplot(x=df['cuisine_type'], y=df['delivery_time'])

# Categorical - day_of_the_week
plt.figure(figsize=(15,8))
sns.boxplot(x=df['day_of_the_week'], y=df['cost_of_the_order'])
# Observation
# There is no cost difference based on day of the week

plt.figure(figsize=(15,8))
sns.boxplot(x=df['day_of_the_week'], y=df['food_preparation_time'])
# Observation
# There is no difference in food preparation time based on day of the week

plt.figure(figsize=(15,8))
sns.boxplot(x=df['day_of_the_week'], y=df['delivery_time'])
# Observation
# It shows delivery time is more in weekday

# Categorical - rating
plt.figure(figsize=(15,8))
sns.boxplot(x=df['rating'], y=df['cost_of_the_order'])

plt.figure(figsize=(15,8))
sns.boxplot(x=df['rating'], y=df['food_preparation_time'])

plt.figure(figsize=(15,8))
sns.boxplot(x=df['rating'], y=df['delivery_time'])

"""### **Question 13:** The company wants to provide a promotional offer in the advertisement of the restaurants. The condition to get the offer is that the restaurants must have a rating count of more than 50 and the average rating should be greater than 4. Find the restaurants fulfilling the criteria to get the promotional offer. [3 marks]"""

# Write the code here
# rating count > 50
# rating > 4
df_rating = df[df['rating'].notna()]
rating_by_rest = df_rating.groupby('restaurant_name')['rating'].agg(['count', 'mean']).reset_index()
restaurants_promotional = rating_by_rest[(rating_by_rest['count'] > 50) & (rating_by_rest['mean'] > 4)]
restaurants_promotional.head()

"""```
# This is formatted as code
```

#### Observations:
The below restaurants get promotional offer since rating count more than 50 & avergae is greater than 4

1. Blue Ribbon Fried Chicken
2. Blue Ribbon Sushi
3. Shake Shack
4. The Meatball Shop

### **Question 14:** The company charges the restaurant 25% on the orders having cost greater than 20 dollars and 15% on the orders having cost greater than 5 dollars. Find the net revenue generated by the company across all orders. [3 marks]
"""

# Write the code here
def cal_charge (amount):
  if amount > 20:
      return amount * 0.25
  elif amount > 5:
      return amount * 0.15
  else:
    return 0

df['final_charge'] = df['cost_of_the_order'].apply(cal_charge)
revenue = df['final_charge'].sum()
print(revenue)

"""#### Observations:

The net revenue generated by the company across all orders 6166 dollars

### **Question 15:** The company wants to analyze the total time required to deliver the food. What percentage of orders take more than 60 minutes to get delivered from the time the order is placed? (The food has to be prepared and then delivered.) [2 marks]
"""

# Write the code here
df['total'] = df['food_preparation_time'] + df['delivery_time']
df_total_greater_60 = df[df['total'] > 60]
df_total_greater_60_per = (df_total_greater_60.shape[0] / df.shape[0]) * 100
print(round(df_total_greater_60_per, 0),'%')

"""#### Observations:

There are 11% of orders take more than 60 minutes to get delivered from the time the order is placed

### **Question 16:** The company wants to analyze the delivery time of the orders on weekdays and weekends. How does the mean delivery time vary during weekdays and weekends? [2 marks]
"""

# Write the code here
mean_delivery_time = df.groupby('day_of_the_week')['delivery_time'].mean()
print(mean_delivery_time)

"""#### Observations:

The average delivery time during weekday is 28 minutes
The average delivery time during weekend is 22 minutes

### Conclusion and Recommendations

### **Question 17:** What are your conclusions from the analysis? What recommendations would you like to share to help improve the business? (You can use cuisine type and feedback ratings to drive your business recommendations.) [6 marks]

### Conclusions:
1. Customers ordered more foods from American cuisines with 584 orders. The next highest is Japanese with 470 orders. The least customer preferred cuisine is Vietnamese with 7 orders.

2. Customers ordered most of the food has cost around 12 dollars

3. Customers ordered most of the foods in weekend when compared to weekdays. 1351 orders in weekend & 547 orders in weekday out of 1898 total orders.

4. Customers didn’t provide rating for 736 orders out of 1898 orders.

### Recommendations:

1. Food Hub need to add more American cuisines to get more revenue when compared to other cuisine types
2. Restaurant should introduce more foods around cost range from 11 to 12 dollars, since this is the affordable cost for customers
3. Customers ordered more food in weekend. So Restuarants should give offer in weekdays to get more revenue.
4. Food Hub should give promotional offers to customers for giving rating of the food orders. The rating will give more insights about the business & it will help business to identify the areas to imporove.

---
"""