# -*- coding: utf-8 -*-
"""Full_Code_SuperKart_Model_Deployment_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Y0l30U7K01PQ5v0yjd9RO2B_stMxTnk

# **Problem Statement**

## Business Context

A sales forecast is a prediction of future sales revenue based on historical data, industry trends, and the status of the current sales pipeline. Businesses use the sales forecast to estimate weekly, monthly, quarterly, and annual sales totals. A company needs to make an accurate sales forecast as it adds value across an organization and helps the different verticals to chalk out their future course of action.

Forecasting helps an organization plan its sales operations by region and provides valuable insights to the supply chain team regarding the procurement of goods and materials. An accurate sales forecast process has many benefits which include improved decision-making about the future and reduction of sales pipeline and forecast risks. Moreover, it helps to reduce the time spent in planning territory coverage and establish benchmarks that can be used to assess trends in the future.

## Objective

SuperKart is a retail chain operating supermarkets and food marts across various tier cities, offering a wide range of products. To optimize its inventory management and make informed decisions around regional sales strategies, SuperKart wants to accurately forecast the sales revenue of its outlets for the upcoming quarter.

To operationalize these insights at scale, the company has partnered with a data science firm—not just to build a predictive model based on historical sales data, but to develop and deploy a robust forecasting solution that can be integrated into SuperKart’s decision-making systems and used across its network of stores.

## Data Description

The data contains the different attributes of the various products and stores.The detailed data dictionary is given below.

- **Product_Id** - unique identifier of each product, each identifier having two letters at the beginning followed by a number.
- **Product_Weight** - weight of each product
- **Product_Sugar_Content** - sugar content of each product like low sugar, regular and no sugar
- **Product_Allocated_Area** - ratio of the allocated display area of each product to the total display area of all the products in a store
- **Product_Type** - broad category for each product like meat, snack foods, hard drinks, dairy, canned, soft drinks, health and hygiene, baking goods, bread, breakfast, frozen foods, fruits and vegetables, household, seafood, starchy foods, others
- **Product_MRP** - maximum retail price of each product
- **Store_Id** - unique identifier of each store
- **Store_Establishment_Year** - year in which the store was established
- **Store_Size** - size of the store depending on sq. feet like high, medium and low
- **Store_Location_City_Type** - type of city in which the store is located like Tier 1, Tier 2 and Tier 3. Tier 1 consists of cities where the standard of living is comparatively higher than its Tier 2 and Tier 3 counterparts.
- **Store_Type** - type of store depending on the products that are being sold there like Departmental Store, Supermarket Type 1, Supermarket Type 2 and Food Mart
- **Product_Store_Sales_Total** - total revenue generated by the sale of that particular product in that particular store

# **Installing and Importing the necessary libraries**
"""

#Installing the libraries with the specified versions
!pip install numpy==2.0.2 pandas==2.2.2 scikit-learn==1.6.1 matplotlib==3.10.0 seaborn==0.13.2 joblib==1.4.2 xgboost==2.1.4 requests==2.32.3 huggingface_hub==0.30.1 -q

"""**Note:**

- After running the above cell, kindly restart the notebook kernel (for Jupyter Notebook) or runtime (for Google Colab) and run all cells sequentially from the next cell.

- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in this notebook.
"""

import warnings
warnings.filterwarnings("ignore")

# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd

# For splitting the dataset
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn import metrics


# Libaries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Removes the limit for the number of displayed columns
pd.set_option("display.max_columns", None)
# Sets the limit for the number of displayed rows
pd.set_option("display.max_rows", 100)


# Libraries different ensemble classifiers
from sklearn.ensemble import (
    BaggingRegressor,
    RandomForestRegressor,
    AdaBoostRegressor,
    GradientBoostingRegressor,
)
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor

# Libraries to get different metric scores
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    mean_absolute_percentage_error
)

# To create the pipeline
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline,Pipeline

# To tune different models and standardize
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler,OneHotEncoder

# To serialize the model
import joblib

# os related functionalities
import os

# API request
import requests

# for hugging face space authentication to upload files
from huggingface_hub import login, HfApi

"""# **Loading the dataset**"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/content')

# Load the dataset from a CSV file into a Pandas DataFrame
superkart_data = pd.read_csv("SuperKart.csv",low_memory=False)

# Create a copy of the dataframe
dataset = superkart_data.copy()

"""# **Data Overview**"""

# Display the first five rows of the dataset
dataset.head()

# checking shape of the data
print(f"There are {dataset.shape[0]} rows and {dataset.shape[1]} columns.")

# Display the column names of the dataset
dataset.columns

# checking column datatypes and number of non-null values
dataset.info()

# checking for duplicate values
dataset.duplicated().sum()

"""No duplicates"""

# checking for missing values
dataset.isnull().sum()

"""No missing values

# **Exploratory Data Analysis (EDA)**
"""

# Define the target variable for the regression task
target = 'Product_Store_Sales_Total'

# List of numerical features in the dataset (excluding 'id' as it is an identifier)
numeric_features = [
    'Product_Weight',
    'Product_Allocated_Area',
    'Product_MRP',
    'Store_Establishment_Year'
]

# List of categorical features in the dataset
categorical_features = [
    'Product_Id',
    'Store_Id',
    'Product_Sugar_Content',
    'Product_Type',
    'Store_Size',
    'Store_Location_City_Type',
    'Store_Type'
]

"""## Univariate Analysis"""

# Generate summary statistics for numerical features
dataset[numeric_features].describe()

# Generate summary statistics for categorical features
dataset[categorical_features].describe()

# Let's check the unique values for categorical variables

# list of all categorical variables
cat_col = dataset.select_dtypes(include="object").columns.tolist()

# printing the number of occurrences of each unique value in each categorical column
for column in cat_col:
    print(dataset[column].value_counts(normalize=True))
    print("-" * 50)

"""

*   All the Product_ids are distinct
*   Product sugar content has 4 distinct values
*   Store_id has 4 distinct values
*   Store_location_city_type has 3 distinct values
*   Store_type has 4 distinct values

"""

# Generate summary statistics for the target variable
dataset[target].describe()

# Check the distribution of the target variable
sns.histplot(dataset[target]);

"""Target is normally distributed

## Bivariate Analysis
"""

# Let's check the correlation between numerical columns
plt.figure(figsize=(15, 7))
sns.heatmap(dataset.corr(numeric_only = True), annot=True, vmin=-1, vmax=1, fmt=".2f", cmap="Spectral")
plt.show()

"""

*   Product_weight is highly correlated (0.74) with product_store_sales_total


*   Product_MRP is highly correlated with product_store_sales_total




"""

# Store_Size vs product_store_sales_total
plt.figure(figsize=(15, 7))
sns.boxplot(x="Store_Size", y="Product_Store_Sales_Total", data=dataset)
plt.title("Store_Size vs product_store_sales_total")
plt.show()

"""
*   Store_size has directly proptional with product store total
*   When the store_size is high, product_store_sales_total is high"""

# Store_Type vs product_store_sales_total
plt.figure(figsize=(15, 7))
sns.boxplot(x="Store_Type", y="Product_Store_Sales_Total", data=dataset)
plt.title("Store_Type vs product_store_sales_total")
plt.show()

"""

*   Department store has highest product store sales total
*   Food Mart has lowest product store sales total

"""

# Store_Location_City_Type vs product_store_sales_total
plt.figure(figsize=(15, 7))
sns.boxplot(x="Store_Location_City_Type", y="Product_Store_Sales_Total", data=dataset)
plt.title("Store_Location_City_Type vs product_store_sales_total")
plt.show()

"""*   Tier1 city has highest product store sales total
*   Tier3 city has lowest product store sales total

# **Data Preprocessing**
"""

# dropping unnecessary columns
X_org = dataset[numeric_features + categorical_features]
X = X_org.drop(["Product_Id", "Product_Allocated_Area", "Store_Establishment_Year"], axis=1)
X.info()
Y = dataset[target]

# Splitting data in train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

print("Shape of Training set : ", X_train.shape)
print("Shape of test set : ", X_test.shape)

# Create a preprocessing pipeline for numerical and categorical features
# Create new lists by filtering out the features that were dropped from X
numeric_features_new = [feature for feature in numeric_features if feature not in ['Product_Allocated_Area', 'Store_Establishment_Year']]
categorical_features_new = [feature for feature in categorical_features if feature not in ["Product_Id"]]

preprocessor = make_column_transformer(
    (Pipeline([('num_imputer', SimpleImputer(strategy='median')),
               ('scaler', StandardScaler())]), numeric_features_new),
    (Pipeline([('cat_imputer', SimpleImputer(strategy='most_frequent')),
               ('encoder', OneHotEncoder(handle_unknown='ignore'))]), categorical_features_new)
)

"""# **Model Building**

## Define functions for Model Evaluation
"""

# function to compute adjusted R-squared
def adj_r2_score(predictors, targets, predictions):
    r2 = r2_score(targets, predictions)
    n = predictors.shape[0]
    k = predictors.shape[1]
    return 1 - ((1 - r2) * (n - 1) / (n - k - 1))


# function to compute different metrics to check performance of a regression model
def model_performance_regression(model, predictors, target):
    """
    Function to compute different metrics to check regression model performance

    model: regressor
    predictors: independent variables
    target: dependent variable
    """

    # predicting using the independent variables
    pred = model.predict(predictors)

    r2 = r2_score(target, pred)  # to compute R-squared
    adjr2 = adj_r2_score(predictors, target, pred)  # to compute adjusted R-squared
    rmse = np.sqrt(mean_squared_error(target, pred))  # to compute RMSE
    mae = mean_absolute_error(target, pred)  # to compute MAE
    mape = mean_absolute_percentage_error(target, pred)  # to compute MAPE

    # creating a dataframe of metrics
    df_perf = pd.DataFrame(
        {
            "RMSE": rmse,
            "MAE": mae,
            "R-squared": r2,
            "Adj. R-squared": adjr2,
            "MAPE": mape,
        },
        index=[0],
    )

    return df_perf

"""The ML models to be built can be any two out of the following:
1. Decision Tree
2. Bagging
3. Random Forest
4. AdaBoost
5. Gradient Boosting
6. XGBoost

First Model - RandomForest model
"""

# Define base Random Forest model
rf_model = RandomForestRegressor(random_state=42)

# Create pipeline with preprocessing and Random Forest model
rf_pipeline = make_pipeline(preprocessor, rf_model)

# Train the model pipeline on the training data
rf_pipeline.fit(X_train, y_train)

rf_estimator_model_train_perf = model_performance_regression(rf_pipeline, X_train,y_train)
print("Training performance \n")
rf_estimator_model_train_perf

rf_estimator_model_test_perf = model_performance_regression(rf_pipeline, X_test,y_test)
print("Testing performance \n")
rf_estimator_model_test_perf

"""RandomForest

*   Train data R2 has higher value (0.98) & Test data R2 has nearest value (0.92)
*   The model perfomance is showing good

Second Model - XGBoost model
"""

# Define base XGBoost model
xgb_model = XGBRegressor(random_state=42)

# Create pipeline with preprocessing and XGBoost model
xgb_pipeline = make_pipeline(preprocessor, xgb_model)

# Train the model pipeline on the training data
xgb_pipeline.fit(X_train, y_train)

xgb_estimator_model_train_perf = model_performance_regression(xgb_pipeline, X_train, y_train)
print("Training performance \n")
xgb_estimator_model_train_perf

xgb_estimator_model_test_perf = model_performance_regression(xgb_pipeline, X_test,y_test)
print("Testing performance \n")
xgb_estimator_model_test_perf

"""XGBoost
*   Train data R2 has higher value (0.98) & Test data R2 has nearest value (0.91)

*   The difference is more than previous model

# **Model Performance Improvement - Hyperparameter Tuning**
"""

### Random Forest Regressor - Hyperparameter Tuning
# Choose the type of classifier.
rf_tuned = RandomForestRegressor(random_state=42)

# Create pipeline with preprocessing and XGBoost model
rf_pipeline = make_pipeline(preprocessor, rf_tuned)

# Grid of parameters to choose from (reduced for faster execution)
parameters = {
    'randomforestregressor__max_depth':[5, 6],
    'randomforestregressor__max_features': ['sqrt', None],
    'randomforestregressor__n_estimators': [100, 150]
}

# Type of scoring used to compare parameter combinations
scorer = metrics.make_scorer(metrics.r2_score)

# Run the grid search
grid_obj = GridSearchCV(rf_pipeline, parameters, scoring=scorer,cv=5)
grid_obj = grid_obj.fit(X_train, y_train)

# Set the clf to the best combination of parameters
rf_tuned = grid_obj.best_estimator_

# Fit the best algorithm to the data.
rf_tuned.fit(X_train, y_train)

rf_tuned_model_train_perf = model_performance_regression(rf_tuned, X_train, y_train)
print("Training performance \n")
rf_tuned_model_train_perf

rf_tuned_model_test_perf = model_performance_regression(rf_tuned, X_test, y_test)
print("Testing performance \n")
rf_tuned_model_test_perf

"""RandomForest HyperParameter Tuning

*   The R2 diff between train & test is (0.011101)
*   It shows imporovement from Random Forest model without tuning
"""

#XGBoost Regressor - Hyperparameter Tuning

# Choose the type of classifier.
xgb_tuned = XGBRegressor(random_state=42)

# Create pipeline with preprocessing and XGBoost model
xgb_pipeline = make_pipeline(preprocessor, xgb_tuned)

#Grid of parameters to choose from (reduced for faster execution)
param_grid = {
    'xgbregressor__n_estimators': [50, 100],
    'xgbregressor__max_depth': [3, 4],
    'xgbregressor__colsample_bytree': [0.5, 0.6],
    'xgbregressor__colsample_bylevel': [0.5, 0.6],
    'xgbregressor__learning_rate': [0.05, 0.1],
    'xgbregressor__reg_lambda': [0.5, 0.6]
}

# Type of scoring used to compare parameter combinations
scorer = metrics.make_scorer(metrics.r2_score)

# Run the grid search
grid_obj = GridSearchCV(xgb_pipeline, param_grid, scoring=scorer,cv=5,n_jobs=-1)
grid_obj = grid_obj.fit(X_train, y_train)

# Set the clf to the best combination of parameters
xgb_tuned = grid_obj.best_estimator_

# Fit the best algorithm to the data.
xgb_tuned.fit(X_train, y_train)

xgb_tuned_model_train_perf = model_performance_regression(xgb_tuned, X_train, y_train)
print("Training performance \n")
xgb_tuned_model_train_perf

xgb_tuned_model_test_perf = model_performance_regression(xgb_tuned, X_test, y_test)
print("Testing performance \n")
xgb_tuned_model_test_perf

"""XGBoost Model with Hyperparameter Tuning

*   The R2 difference between train & test is (0.010073)
*   It shows imporovement from XGBoost model without performance tuning

# **Model Performance Comparison, Final Model Selection, and Serialization**
"""

# training performance comparison

models_train_comp_df = pd.concat(
    [rf_estimator_model_train_perf.T,rf_tuned_model_train_perf.T,
    xgb_estimator_model_train_perf.T,xgb_tuned_model_train_perf.T],
    axis=1,
)

models_train_comp_df.columns = [
    "Random Forest Estimator",
    "Random Forest Tuned",
    "XGBoost",
    "XGBoost Tuned"
]

print("Training performance comparison:")
models_train_comp_df

# Testing performance comparison

models_test_comp_df = pd.concat(
    [rf_estimator_model_test_perf.T,rf_tuned_model_test_perf.T,
    xgb_estimator_model_test_perf.T,xgb_tuned_model_test_perf.T],
    axis=1,
)

models_test_comp_df.columns = [
    "Random Forest Estimator",
    "Random Forest Tuned",
    "XGBoost",
    "XGBoost Tuned"
]

print("Testing performance comparison:")
models_test_comp_df

(models_train_comp_df - models_test_comp_df).iloc[2]

"""

*   The tuned XGBoost model achieves the smallest R² score difference between train & test data
*   Considering test performance, generalization, and overall fit, the tuned XGBoost model emerges as the best-performing model overall


*   tuned XGBoost model is the best model for the superkart sales prediction




"""

# Model serialization
# Create a folder to upload your trained serialized model into it
os.makedirs("backend_files", exist_ok=True)

# Define the file path to save (serialize) the trained model along with the data preprocessing steps
saved_model_path = "backend_files/superkart_prediction_model_v1_0.joblib"

# Save the best trained model pipeline using joblib
joblib.dump(xgb_tuned, saved_model_path)

print(f"Model saved successfully at {saved_model_path}")

# Load the saved model pipeline from the file
saved_model = joblib.load("backend_files/superkart_prediction_model_v1_0.joblib")

# Confirm the model is loaded
print("Model loaded successfully.")

saved_model.predict(X_test)

"""The model is used for making prediction without retraining

# **Deployment - Backend**

## Flask Web Framework
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile backend_files/app.py
# # Import necessary libraries
# import numpy as np
# import joblib
# import pandas as pd
# from flask import Flask, request, jsonify
# 
# # Initialize the Flask application
# superkart_api = Flask("Superkart Predictor")
# 
# # Load the trained model
# model = joblib.load("superkart_prediction_model_v1_0.joblib")
# 
# # Root endpoint
# @superkart_api.route('/', methods=['GET'])
# def home():
#     return "Welcome to the Superkart Prediction API!"
# 
# # Single property prediction endpoint
# @superkart_api.route('/v1/superkartpredict', methods=['POST'])
# def superkart_prediction():
#     try:
#         data = request.get_json()
# 
#         # Convert JSON to DataFrame
#         sample = {
#             'Product_Weight': data['Product_Weight'],
#             'Product_MRP': data['Product_MRP'],
#             'Store_Id': data['Store_Id'],
#             'Product_Sugar_Content': data['Product_Sugar_Content'],
#             'Product_Type': data['Product_Type'],
#             'Store_Size': data['Store_Size'],
#             'Store_Type': data['Store_Type'],
#             'Store_Location_City_Type': data['Store_Location_City_Type'],
#         }
# 
#         input_data = pd.DataFrame([sample])
# 
#         # Predict
#         prediction = model.predict(input_data).tolist()[0]
# 
#         return jsonify({'Predicted_sales': prediction})
# 
#     except Exception as e:
#         return jsonify({'error': str(e)}), 400
#

"""## Dependencies File"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile backend_files/requirements.txt
# pandas==2.2.2
# numpy==2.0.2
# scikit-learn==1.6.1
# xgboost==2.1.4
# joblib==1.4.2
# Werkzeug==2.2.2
# flask==2.2.2
# gunicorn==20.1.0
# requests==2.28.1
# uvicorn[standard]

"""## Dockerfile"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile backend_files/Dockerfile
# FROM python:3.9-slim
# 
# # Set the working directory inside the container
# WORKDIR /app
# 
# # Copy all files from the current directory to the container's working directory
# COPY . .
# 
# # Install dependencies from the requirements file without using cache to reduce image size
# RUN pip install --no-cache-dir --upgrade -r requirements.txt
# 
# # Define the command to start the application using Gunicorn with 4 worker processes
# # - `-w 4`: Uses 4 worker processes for handling requests
# # - `-b 0.0.0.0:7860`: Binds the server to port 7860 on all network interfaces
# # - `app:app`: Runs the Flask app (assuming `app.py` contains the Flask instance named `app`)
# CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:7860", "app:superkart_api"]

"""## Setting up a Hugging Face Docker Space for the Backend"""

!pip install python-dotenv

# Load ApiKeys.env file
from dotenv import load_dotenv
load_dotenv("ApiKeys.env")

HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")

login(token=HUGGINGFACE_API_KEY)

# Import the create_repo function from the huggingface_hub library
from huggingface_hub import create_repo

# Try to create the repository for the Hugging Face Space
try:
    create_repo("SuperKartPredictionBackendNew",  # One can replace "Backend_Docker_space" with the desired space name
        repo_type="space",  # Specify the repository type as "space"
        space_sdk="docker",  # Specify the space SDK as "docker" to create a Docker space
        private=False  # Set to True if you want the space to be private
    )
except Exception as e:
    # Handle potential errors during repository creation
    if "RepositoryAlreadyExistsError" in str(e):
        print("Repository already exists. Skipping creation.")
    else:
        print(f"Error creating repository: {e}")

"""## Uploading Files to Hugging Face Space (Docker Space)"""

# for hugging face space authentication to upload files
from huggingface_hub import HfApi, get_full_repo_name

# Ensure the user is logged in
from dotenv import load_dotenv
load_dotenv("ApiKeys.env")

HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")

login(token=HUGGINGFACE_API_KEY)

# Initialize the API
api = HfApi()

# Get the authenticated user's ID to construct the repo_id dynamically
user_info = api.whoami()
current_user = user_info["name"]

# The space name should match what was used in create_repo in the previous cell
space_name = "SuperKartPredictionBackendNew"
repo_id = f"{current_user}/{space_name}"

print(f"Attempting to upload to repository: {repo_id}")

# Upload Streamlit app files stored in the folder called deployment_files
api.upload_folder(
    folder_path="backend_files",  # Local folder path
    repo_id=repo_id,  # Hugging face space id, dynamically constructed
    repo_type="space",  # Hugging face repo type "space"
)

"""# Huggingface Space Backend
https://huggingface.co/spaces/sindhuja123/SuperKartPredictionBackendNew

# **Deployment - Frontend**

## Points to note before executing the below cells
- Create a Streamlit space on Hugging Face by following the instructions provided on the content page titled **`Creating Spaces and Adding Secrets in Hugging Face`** from Week 1

## Streamlit for Interactive UI
"""

# Create a folder for storing the files needed for frontend UI deployment
os.makedirs("frontend_files", exist_ok=True)
os.makedirs("frontend_files/.streamlit", exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile frontend_files/app.py
# import streamlit as st
# import pandas as pd
# import requests
# 
# # Set the title of the Streamlit app
# st.title("Superkart Space Prediction")
# 
# # Define the backend base URL (use your actual backend Space)
# backend_url = "https://sindhuja123-superkartpredictionbackendnew.hf.space" # Change this to your backend URL
# 
# # Section for online prediction
# st.subheader("Online Prediction")
# 
# # Collect user input
# Product_Weight = st.number_input("Product Weight", min_value=0.0)
# Product_MRP = st.number_input("Product MRP", min_value=0.0)
# Store_Id = st.selectbox("Store Id", ["OUT004", "OUT001", "OUT003", "OUT002"])
# Product_Sugar_Content = st.selectbox("Product Sugar Content", ["Low Sugar", "Regular", "No Sugar"])
# Product_Type = st.selectbox("Product Type", ["Fruits and Vegetables", "Snack Foods", "Frozen Foods", "Dairy", "Household", "Baking Goods", "Canned", "Health and Hygiene", "Meat", "Soft Drinks", "Breads", "Hard Drinks", "Others", "Starchy Foods", "Breakfast", "Seafood"])
# Store_Size = st.selectbox("Store Size", ["Small", "Medium", "High"])
# Store_Type = st.selectbox("Store Type", ["Supermarket Type2", "Supermarket Type1", "Departmental Store", "Food Mart"])
# Store_Location_City_Type = st.selectbox("Store Location City Type", ["Tier 1", "Tier 2", "Tier 3"])
# 
# # Convert user input to payload
# payload = {
#     'Product_Weight': Product_Weight,
#     'Product_MRP': Product_MRP,
#     'Store_Id': Store_Id,
#     'Product_Sugar_Content': Product_Sugar_Content,
#     'Product_Type': Product_Type,
#     'Store_Size': Store_Size,
#     'Store_Type': Store_Type,
#     'Store_Location_City_Type': Store_Location_City_Type
# }
# 
# # Make prediction
# if st.button("Predict"):
#     try:
#         response = requests.post(f"{backend_url}/v1/superkartpredict", json=payload)
# 
#         if response.status_code == 200:
#             result = response.json()
#             st.write(f"Predicted Sales: ${result['Predicted_sales']}")
#         else:
#             st.error(f"Prediction failed. Status code: {response.status_code}")
#     except Exception as e:
#         st.error(f"Exception during request: {e}")

"""## Dependencies File"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile frontend_files/requirements.txt
# pandas==2.2.2
# requests==2.28.1
# streamlit==1.43.2

"""## DockerFile"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile frontend_files/Dockerfile
# # Use a minimal base image with Python 3.9 installed
# FROM python:3.9-slim
# 
# # Set the working directory inside the container to /app
# WORKDIR /app
# 
# # Copy all files from the current directory on the host to the container's /app directory
# COPY . .
# 
# # Install Python dependencies listed in requirements.txt
# RUN pip3 install -r requirements.txt
# 
# # Define the command to run the Streamlit app on port 8501 and make it accessible externally
# CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0", "--server.enableXsrfProtection=false"]
# 
# # NOTE: Disable XSRF protection for easier external access in order to make batch predictions

# Commented out IPython magic to ensure Python compatibility.
# %%writefile frontend_files/.streamlit/config.toml
# [server]
# headless = true
# port = 7860
# enableCORS = false
# enableXsrfProtection = false

"""## Uploading Files to Hugging Face Space (Streamlit Space)"""

# Try to create the repository for the Hugging Face Space
try:
    create_repo("SuperKartPredictionFrontendNew",  # One can replace "Backend_Docker_space" with the desired space name
        repo_type="space",  # Specify the repository type as "space"
        space_sdk="docker",  # Specify the space SDK as "docker" to create a Docker space
        private=False  # Set to True if you want the space to be private
    )
except Exception as e:
    # Handle potential errors during repository creation
    if "RepositoryAlreadyExistsError" in str(e):
        print("Repository already exists. Skipping creation.")
    else:
        print(f"Error creating repository: {e}")

# for hugging face space authentication to upload files
from huggingface_hub import HfApi, get_full_repo_name

# Ensure the user is logged in
from dotenv import load_dotenv
load_dotenv("ApiKeys.env")

HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")

login(token=HUGGINGFACE_API_KEY)

# Initialize the API
api = HfApi()

# Get the authenticated user's ID to construct the repo_id dynamically
user_info = api.whoami()
current_user = user_info["name"]

# The space name should match what was used in create_repo in the previous cell
space_name = "SuperKartPredictionFrontendNew"
repo_id = f"{current_user}/{space_name}"

print(f"Attempting to upload to repository: {repo_id}")

# Upload Streamlit app files stored in the folder called deployment_files
api.upload_folder(
    folder_path="frontend_files",  # Local folder path
    repo_id=repo_id,  # Hugging face space id, dynamically constructed
    repo_type="space",  # Hugging face repo type "space"
)

"""# Hugging Face Space Frontend
https://huggingface.co/spaces/sindhuja123/SuperKartPredictionFrontendNew
"""

#Use only BE for prediction
import json  # To handle JSON formatting for API requests and responses
import requests  # To send HTTP requests to the deployed Flask API

import pandas as pd  # For data manipulation and analysis
import numpy as np  # For numerical computations

model_root_url = "https://sindhuja123-superkartpredictionbackendnew.hf.space"  # Base URL of the deployed Flask API on Hugging Face Space; enter user name and space name before running the cell

model_url = model_root_url + "/v1/superkartpredict"  # Endpoint for online (single) inference

payload = {
    'Product_Weight': 0.02,
    'Product_MRP': 0.03,
    'Store_Id': "OUT004",
    'Product_Sugar_Content': "Low Sugar",
    'Product_Type': "Fruits and Vegetables",
    'Store_Size': "Small",
    'Store_Type': "Supermarket Type2",
    'Store_Location_City_Type': "Tier 1"
}

response = requests.post(model_url, json=payload)

response

print(response.json())

"""# **Actionable Insights and Business Recommendations**

# Huggingface Space Urls
https://huggingface.co/spaces/sindhuja123/SuperKartPredictionBackendNew
https://huggingface.co/spaces/sindhuja123/SuperKartPredictionFrontendNew


# Actionable Insights

*   Store_size - Larger stores generate higher revenue

*   Store_Location_City_Type - Tier 1 locations generate higher revenue

*   Store_type - Department Store generate higher revenue

# Business Recommendations


*   Allocate more space to high-performing products and reduce overstock of
slow movers.

*   Use premium pricing in Tier 1 cities and value pricing in Tier 2/3.

*   Place high-margin products prominently and group complementary items.

*   Adjust stock and SKU variety based on store size and city tier.

*   Use the final model predictions with supply chain to automate restocking.
"""