# -*- coding: utf-8 -*-
"""INN_ReneWind_Main_Project_FullCode_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2B2lUeyZ4ccP44bfNev78xcYDpE9lLc

# **Problem Statement**

## Business Context

Renewable energy sources play an increasingly important role in the global energy mix, as the effort to reduce the environmental impact of energy production increases.

Out of all the renewable energy alternatives, wind energy is one of the most developed technologies worldwide. The U.S Department of Energy has put together a guide to achieving operational efficiency using predictive maintenance practices.

Predictive maintenance uses sensor information and analysis methods to measure and predict degradation and future component capability. The idea behind predictive maintenance is that failure patterns are predictable and if component failure can be predicted accurately and the component is replaced before it fails, the costs of operation and maintenance will be much lower.

The sensors fitted across different machines involved in the process of energy generation collect data related to various environmental factors (temperature, humidity, wind speed, etc.) and additional features related to various parts of the wind turbine (gearbox, tower, blades, break, etc.).

## Objective

“ReneWind” is a company working on improving the machinery/processes involved in the production of wind energy using machine learning and has collected data of generator failure of wind turbines using sensors. They have shared a ciphered version of the data, as the data collected through sensors is confidential (the type of data collected varies with companies). Data has 40 predictors, 20000 observations in the training set and 5000 in the test set.

The objective is to build various classification models, tune them, and find the best one that will help identify failures so that the generators could be repaired before failing/breaking to reduce the overall maintenance cost.
The nature of predictions made by the classification model will translate as follows:

- True positives (TP) are failures correctly predicted by the model. These will result in repairing costs.
- False negatives (FN) are real failures where there is no detection by the model. These will result in replacement costs.
- False positives (FP) are detections where there is no failure. These will result in inspection costs.

It is given that the cost of repairing a generator is much less than the cost of replacing it, and the cost of inspection is less than the cost of repair.

“1” in the target variables should be considered as “failure” and “0” represents “No failure”.

## Data Description

The data provided is a transformed version of the original data which was collected using sensors.

- Train.csv - To be used for training and tuning of models.
- Test.csv - To be used only for testing the performance of the final best model.

Both the datasets consist of 40 predictor variables and 1 target variable.

# **Installing and Importing the necessary libraries**
"""

# Installing the libraries with the specified version
!pip install --no-deps tensorflow==2.18.0 scikit-learn==1.3.2 matplotlib===3.8.3 seaborn==0.13.2 numpy==1.26.4 pandas==2.2.2 -q --user --no-warn-script-location

# Library for data manipulation and analysis.
import pandas as pd
# Fundamental package for scientific computing.
import numpy as np
#splitting datasets into training and testing sets.
from sklearn.model_selection import train_test_split
#Imports tools for data preprocessing including label encoding, one-hot encoding, and standard scaling
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,StandardScaler
#Imports a class for imputing missing values in datasets.
from sklearn.impute import SimpleImputer
#Imports the Matplotlib library for creating visualizations.
import matplotlib.pyplot as plt
# Imports the Seaborn library for statistical data visualization.
import seaborn as sns
# Time related functions.
import time
#Imports functions for evaluating the performance of machine learning models
from sklearn.metrics import confusion_matrix, f1_score,accuracy_score, recall_score, precision_score, classification_report


#Imports the tensorflow,keras and layers.
import tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dense, Input, Dropout,BatchNormalization
from tensorflow.keras import backend

# to suppress unnecessary warnings
import warnings
warnings.filterwarnings("ignore")

"""**Note**:
- After running the above cell, kindly restart the runtime (for Google Colab) or notebook kernel (for Jupyter Notebook), and run all cells sequentially from the next cell.
- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in ***this notebook***.

# **Loading the Data**
"""

# uncomment and run the following lines for Google Colab
from google.colab import drive
drive.mount('/content/drive')

#Reading the dataset.
Data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/content/Train.csv')
Data_Test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/content/Test.csv')

Data_Train_Copy = Data.copy()
Data_Test_Copy = Data_Test.copy()

"""# **Data Overview**"""

# Let's view the first 5 rows of the data
Data.head()

# Checking the number of rows and columns in the data
Data.shape

"""The dataset has 20000 rows and 41 columns"""

# Let's check the datatypes of the columns in the dataset
Data.info()

"""
1.   There are 20000 observations & 41 columns
2.   40 columns are in float datatype & 1 column is numerical


"""

# Let's check for duplicate values in the data
Data.duplicated().sum()

"""No duplicated in this dataset"""

# Let's check for missing values in the data
round(Data.isnull().sum() / Data.isnull().count() * 100, 2)

"""V1 & V2 columns has some missing values"""

Data["Target"].value_counts(1)

"""It shows 94% of data has replacement(No failure) as No, 5% of data has replacement(failure) as YES in training data set"""

# Let's view the statistical summary of the numerical columns in the data
Data.describe().T

# Let's check the number of unique values in each column
Data.nunique()

"""All comlumns has unique value except Target column (which is the output)

# **Exploratory Data Analysis**
"""

# Function to create labeled barplots


def labeled_barplot(data, feature, perc=False, n=None):
    """
    Barplot with percentage at the top

    data: dataframe
    feature: dataframe column
    perc: whether to display percentages instead of count (default is False)
    n: displays the top n category levels (default is None, i.e., display all levels)
    """

    total = len(data[feature])  # length of the column
    count = data[feature].nunique()
    if n is None:
        plt.figure(figsize=(count + 1, 5))
    else:
        plt.figure(figsize=(n + 1, 5))

    plt.xticks(rotation=90, fontsize=15)
    ax = sns.countplot(
        data=data,
        x=feature,
        palette="Paired",
        order=data[feature].value_counts().index[:n].sort_values(),
    )

    for p in ax.patches:
        if perc == True:
            label = "{:.1f}%".format(
                100 * p.get_height() / total
            )  # percentage of each class of the category
        else:
            label = p.get_height()  # count of each level of the category

        x = p.get_x() + p.get_width() / 2  # width of the plot
        y = p.get_height()  # height of the plot

        ax.annotate(
            label,
            (x, y),
            ha="center",
            va="center",
            size=12,
            xytext=(0, 5),
            textcoords="offset points",
        )  # annotate the percentage

    plt.show()  # show the plot

# Function to plot a boxplot and a histogram along the same scale.


def histogram_boxplot(data, feature, figsize=(12, 7), kde=False, bins=None):
    """
    Boxplot and histogram combined

    data: dataframe
    feature: dataframe column
    figsize: size of figure (default (12,7))
    kde: whether to the show density curve (default False)
    bins: number of bins for histogram (default None)
    """
    f2, (ax_box2, ax_hist2) = plt.subplots(
        nrows=2,  # Number of rows of the subplot grid= 2
        sharex=True,  # x-axis will be shared among all subplots
        gridspec_kw={"height_ratios": (0.25, 0.75)},
        figsize=figsize,
    )  # creating the 2 subplots
    sns.boxplot(
        data=data, x=feature, ax=ax_box2, showmeans=True, color="violet"
    )  # boxplot will be created and a star will indicate the mean value of the column
    sns.histplot(
        data=data, x=feature, kde=kde, ax=ax_hist2, bins=bins, palette="winter"
    ) if bins else sns.histplot(
        data=data, x=feature, kde=kde, ax=ax_hist2
    )  # For histogram
    ax_hist2.axvline(
        data[feature].mean(), color="green", linestyle="--"
    )  # Add mean to the histogram
    ax_hist2.axvline(
        data[feature].median(), color="black", linestyle="-"
    )  # Add median to the histogram

### Function to plot distributions


def distribution_plot_wrt_target(data, predictor, target):

    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    target_uniq = data[target].unique()

    axs[0, 0].set_title("Distribution of target for target=" + str(target_uniq[0]))
    sns.histplot(
        data=data[data[target] == target_uniq[0]],
        x=predictor,
        kde=True,
        ax=axs[0, 0],
        color="teal",
    )

    axs[0, 1].set_title("Distribution of target for target=" + str(target_uniq[1]))
    sns.histplot(
        data=data[data[target] == target_uniq[1]],
        x=predictor,
        kde=True,
        ax=axs[0, 1],
        color="orange",
    )

    axs[1, 0].set_title("Boxplot w.r.t target")
    sns.boxplot(data=data, x=target, y=predictor, ax=axs[1, 0], palette="gist_rainbow")

    axs[1, 1].set_title("Boxplot (without outliers) w.r.t target")
    sns.boxplot(
        data=data,
        x=target,
        y=predictor,
        ax=axs[1, 1],
        showfliers=False,
        palette="gist_rainbow",
    )

    plt.tight_layout()
    plt.show()

# function to plot stacked bar chart


def stacked_barplot(data, predictor, target):
    """
    Print the category counts and plot a stacked bar chart

    data: dataframe
    predictor: independent variable
    target: target variable
    """
    count = data[predictor].nunique()
    sorter = data[target].value_counts().index[-1]
    tab1 = pd.crosstab(data[predictor], data[target], margins=True).sort_values(
        by=sorter, ascending=False
    )
    print(tab1)
    print("-" * 120)
    tab = pd.crosstab(data[predictor], data[target], normalize="index").sort_values(
        by=sorter, ascending=False
    )
    tab.plot(kind="bar", stacked=True, figsize=(count + 1, 5))
    plt.legend(
        loc="lower left",
        frameon=False,
    )
    plt.legend(loc="upper left", bbox_to_anchor=(1, 1))
    plt.show()

"""## Univariate analysis"""

for feature in Data.columns:
    histogram_boxplot(Data, feature)

"""## Bivariate Analysis"""

plt.figure(figsize=(40, 40))
sns.heatmap(Data.corr(numeric_only = True), annot=True, vmin=-1, vmax=1, fmt=".2f", cmap="Spectral")

"""Correlation shows "Target" has high correclation with these columns V7, V15, V16

# **Data Preprocessing**
"""

# drop target variable
X = Data_Train_Copy.drop("Target", axis=1)
y = Data_Train_Copy["Target"]

#split the main train set into train and validation

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.25, random_state=1, stratify=y
)

# Split the teat data into X & y
X_test = Data_Test_Copy.drop("Target", axis=1)
y_test =  Data_Test_Copy["Target"]

print(X_train.shape, X_val.shape)
print(X_test.shape)

"""

1.   No of rows in train data = 15000
2.   No of rows in validation data = 5000
3.   No of rows in test data = 5000

"""

# Missing value imputation

X_train.columns

#Calculating the total number of nan values for each columns.
X_train.isnull().sum()

"""V1 & V2 has missing values"""

imputer_median = SimpleImputer(strategy="median")

# Fit and transform the train data
X_train = pd.DataFrame(imputer_median.fit_transform(X_train), columns=X_train.columns)

# Transform the validation data
X_val = pd.DataFrame(imputer_median.transform(X_val), columns=X_train.columns)    # Complete the code to impute missing values in the validation set while accounting for data leakage

# Transform the test data
X_test = pd.DataFrame(imputer_median.transform(X_test), columns=X_train.columns)    # Complete the code to impute missing values in the test set while accounting for data leakage

#Calculating the total number of nan values for each columns.
X_train.isnull().sum()

"""There is no missing values after imputation

# **Model Building**
"""

def plot(history, name):
    """
    Function to plot loss/accuracy

    history: an object which stores the metrics and losses.
    name: can be one of Loss or Accuracy
    """
    fig, ax = plt.subplots() #Creating a subplot with figure and axes.
    plt.plot(history.history[name]) #Plotting the train accuracy or train loss
    plt.plot(history.history['val_'+name]) #Plotting the validation accuracy or validation loss

    plt.title('Model ' + name.capitalize()) #Defining the title of the plot.
    plt.ylabel(name.capitalize()) #Capitalizing the first letter.
    plt.xlabel('Epoch') #Defining the label for the x-axis.
    fig.legend(['Train', 'Validation'], loc="outside right upper") #Defining the legend, loc controls the position of the legend.

# defining a function to compute different metrics to check performance of a classification model built using statsmodels
def model_performance_classification(
    model, predictors, target, threshold=0.5
):
    """
    Function to compute different metrics to check classification model performance

    model: classifier
    predictors: independent variables
    target: dependent variable
    threshold: threshold for classifying the observation as class 1
    """

    # checking which probabilities are greater than threshold
    pred = model.predict(predictors) > threshold
    # pred_temp = model.predict(predictors) > threshold
    # # rounding off the above values to get classes
    # pred = np.round(pred_temp)

    acc = accuracy_score(target, pred)  # to compute Accuracy
    recall = recall_score(target, pred, average='weighted')  # to compute Recall
    precision = precision_score(target, pred, average='weighted')  # to compute Precision
    f1 = f1_score(target, pred, average='weighted')  # to compute F1-score

    # creating a dataframe of metrics
    df_perf = pd.DataFrame(
        {"Accuracy": acc, "Recall": recall, "Precision": precision, "F1 Score": f1,},
        index=[0],
    )

    return df_perf

"""## Model Evaluation Criterion

The main objective is to find the best model that will help identify failures so that the generators could be repaired before failing/breaking to reduce the overall maintenance cost

**which is more important?**
False negatives (FN) are real failures where there is no detection by the model. These will result in replacement costs.

So we need to reduce False Negative

We need to conside higher "Recall" to reduce False Negative

## Initial Model Building (Model 0)

- Let's start with a neural network consisting of
  - just one hidden layer
  - activation function of ReLU
  - SGD as the optimizer
"""

# Calculate class weights for imbalanced dataset
cw = (y_train.shape[0]) / np.bincount(y_train)

# Create a dictionary mapping class indices to their respective class weights
cw_dict = {}
for i in range(cw.shape[0]):
    cw_dict[i] = cw[i]

cw_dict

# defining the batch size and # epochs upfront as we'll be using the same values for all models
epochs = 25
batch_size = 64

# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network with one hidden layer & ReLU activation function in hidden layer
#Model0 - One hidden layer & activation function - ReLU & SGD optimizer

model0 = Sequential()
model0.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model0.add(Dense(1,activation="sigmoid"))

model0.summary()

optimizer = tf.keras.optimizers.SGD()    # defining SGD as the optimizer to be used
model0.compile(loss='binary_crossentropy', optimizer=optimizer, metrics = ['Recall'])

start = time.time()
history = model0.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_0_train_perf = model_performance_classification(model0, X_train, y_train)
model_0_train_perf

model_0_valid_perf = model_performance_classification(model0, X_val, y_val)
model_0_valid_perf

"""Train data Recall is ~0.97. Validation data Recall is ~0.97. The differnet between Train data Recall & Validation data Recall is less.

It looks like a good model . Lets try some improvement in next section.

# **Model Performance Improvement**

## Model 1
"""

# Adding momentum & extra hidden layer
# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model1 - two hidden layer & activation function - ReLU & SGD optimizer with momentum
model1 = Sequential()
model1.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model1.add(Dense(7,activation="relu"))
model1.add(Dense(1,activation="sigmoid"))

model1.summary()

optimizer = tf.keras.optimizers.SGD(momentum=0.9)    # defining SGD as the optimizer to be used
model1.compile(loss='binary_crossentropy', optimizer=optimizer)

start = time.time()
history = model1.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight = cw_dict)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_1_train_perf = model_performance_classification(model1, X_train, y_train)
model_1_train_perf

model_1_valid_perf = model_performance_classification(model1, X_val, y_val)
model_1_valid_perf

"""Train Recall is ~0.98. Validation Recall is ~0.98. The performance has improved from previous model.
It looks like a good model . Lets try some improvement in next section.

## Model 2
"""

# use adam optimizer

# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model2 - two hidden layer & activation function - ReLU & Adam optimizer

model2 = Sequential()
model2.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model2.add(Dense(7,activation="relu"))
model2.add(Dense(1,activation="sigmoid"))

model2.summary()

optimizer = tf.keras.optimizers.Adam()    # defining Adam as the optimizer to be used
model2.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=[tf.keras.metrics.Recall()])

# train the model with full history include all the metrics
start = time.time()
history = model2.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict, verbose=1)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_2_train_perf = model_performance_classification(model2, X_train, y_train)
model_2_train_perf

model_2_valid_perf = model_performance_classification(model2, X_val, y_val)
model_2_valid_perf

"""*Train* Recall is ~0.97. Validation Recall is ~0.96.


There is no improved in the performance when compared to previous models - model 0 & model 1

## Model 3
"""

# use dropout
# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model3- two hidden layer & activation function - ReLU & Adam optimizer with dropout

model3 = Sequential()
model3.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model3.add(Dropout(0.4))
model3.add(Dense(7,activation="relu"))
model3.add(Dropout(0.2))
model3.add(Dense(1,activation="sigmoid"))

model3.summary()

optimizer = tf.keras.optimizers.Adam()    # defining Adam as the optimizer to be used
model3.compile(loss='binary_crossentropy', optimizer=optimizer)

start = time.time()
history = model3.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict)
end=time.time()

plot(history,'loss')

model_3_train_perf = model_performance_classification(model3, X_train, y_train)
model_3_train_perf

model_3_valid_perf = model_performance_classification(model3, X_val, y_val)
model_3_valid_perf

"""The difference between Train data recall & validation data recall is less

## Model 4
"""

#Let's add batch normalization
# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model4- two hidden layer & activation function - ReLU & Adam optimizer with batch normalization

model4 = Sequential()
model4.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model4.add(BatchNormalization())
model4.add(Dense(7,activation="relu"))
model4.add(BatchNormalization())
model4.add(Dense(1,activation="sigmoid"))

model4.summary()

optimizer = tf.keras.optimizers.Adam()    # defining Adam as the optimizer to be used
model4.compile(loss='binary_crossentropy', optimizer=optimizer)

start = time.time()
history = model4.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_4_train_perf = model_performance_classification(model4, X_train, y_train)
model_4_train_perf

model_4_valid_perf = model_performance_classification(model4, X_val, y_val)
model_4_valid_perf

"""Recall value is incresed from previous model model3. The difference between test recall & validation recall is less.

## Model 5
"""

# lets add both batch normalization & dropout
# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model5- two hidden layer & activation function - ReLU & Adam optimizer with batch normalization & dropout
model5 = Sequential()
model5.add(Dense(14,activation="relu",input_dim=X_train.shape[1]))
model5.add(BatchNormalization())
model5.add(Dropout(0.4))
model5.add(Dense(7,activation="relu"))
model5.add(BatchNormalization())
model5.add(Dropout(0.2))
model5.add(Dense(1,activation="sigmoid"))

model5.summary()

optimizer = tf.keras.optimizers.Adam()    # defining Adam as the optimizer to be used
model5.compile(loss='binary_crossentropy', optimizer=optimizer)

start = time.time()
history = model5.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_5_train_perf = model_performance_classification(model5, X_train, y_train)
model_5_train_perf

model_5_valid_perf = model_performance_classification(model5, X_val, y_val)
model_5_valid_perf

"""Recall value is decresed from previous model model4

## Model 6
"""

# lets initialize the weights using He normal & dropout
# clears the current Keras session, resetting all layers and models previously created, freeing up memory and resources.
tf.keras.backend.clear_session()

#Initializing the neural network
#Model6-  two hidden layer & activation function - ReLU & Adam optimizer with He normal & dropout

model6 = Sequential()
model6.add(Dense(14,activation="relu",kernel_initializer="he_normal",input_dim=X_train.shape[1]))
model6.add(Dropout(0.4))
model6.add(Dense(7,activation="relu",kernel_initializer="he_normal"))
model6.add(Dropout(0.2))
model6.add(Dense(1,activation="sigmoid",kernel_initializer="he_normal"))

model6.summary()

optimizer = tf.keras.optimizers.Adam()    # defining Adam as the optimizer to be used
model6.compile(loss='binary_crossentropy', optimizer=optimizer)

start = time.time()
history = model6.fit(X_train, y_train, validation_data=(X_val,y_val) , batch_size=batch_size, epochs=epochs,class_weight=cw_dict)
end=time.time()

print("Time taken in seconds ",end-start)

plot(history,'loss')

model_6_train_perf = model_performance_classification(model6, X_train, y_train)
model_6_train_perf

model_6_valid_perf = model_performance_classification(model6, X_val, y_val)
model_6_valid_perf

"""There is no performance improvement when compared to previous models

# **Model Performance Comparison and Final Model Selection**

Now, in order to select the final model, we will compare the performances of all the models for the training and validation sets.
"""

# training performance comparison

models_train_comp_df = pd.concat(
    [
        model_0_train_perf.T,
        model_1_train_perf.T,
        model_2_train_perf.T,
        model_3_train_perf.T,
        model_4_train_perf.T,
        model_5_train_perf.T,
        model_6_train_perf.T
    ],
    axis=1,
)
models_train_comp_df.columns = [
    "Neural Network (Model0 - One hidden layer, SGD, No Regularization)",
    "Neural Network (Model1 - Two hidden layer, SGD with Momentum, No Regularization)",
    "Neural Network (Model2 - Two hidden layer, Adam, No Regularization)",
    "Neural Network (Model3 - Two hidden layer, Adam, dropout [0.4,0.2])",
    "Neural Network (Model4 - Two hidden layer, Adam, Batch Normalization)",
    "Neural Network (Model5 - Two hidden layer, Adam, dropout [0.4,0.2], Batch Normalization)",
    "Neural Network (Model6 - Two hidden layer, Adam,dropout [0.4,0.2] ,He initialization)"
]

#Validation performance comparison

models_valid_comp_df = pd.concat(
    [
        model_0_valid_perf.T,
        model_1_valid_perf.T,
        model_2_valid_perf.T,
        model_3_valid_perf.T,
        model_4_valid_perf.T,
        model_5_valid_perf.T,
        model_6_valid_perf.T
    ],
    axis=1,
)
models_valid_comp_df.columns = [
    "Neural Network (Model0 - One hidden layer, SGD, No Regularization)",
    "Neural Network (Model1 - Two hidden layer, SGD with Momentum, No Regularization)",
    "Neural Network (Model2 - Two hidden layer, Adam, No Regularization)",
    "Neural Network (Model3 - Two hidden layer, Adam, dropout [0.4,0.2])",
    "Neural Network (Model4 - Two hidden layer, Adam, Batch Normalization)",
    "Neural Network (Model5 - Two hidden layer, Adam, dropout [0.4,0.2], Batch Normalization)",
    "Neural Network (Model6 - Two hidden layer, Adam,dropout [0.4,0.2] ,He initialization)"
]

models_train_comp_df

models_valid_comp_df

models_train_comp_df.loc["Recall"] - models_valid_comp_df.loc["Recall"]

"""Final Model: Neural Network (Adam, Batch Normalization) - Model4

Reasoning:



1.   The recall difference between test & validation data is : -0.000733 , which is less when compared to other models
2.   It shows good performance & it will predict the machine failure correctly

Now, let's check the performance of the final model on the test set.
"""

# test final model with Test data
y_train_pred = model4.predict(X_train)
y_valid_pred = model4.predict(X_val)
y_test_pred = model4.predict(X_test)

print("Classification Report - Train data",end="\n\n")
cr = classification_report(y_train,y_train_pred>0.5)
print(cr)

print("Classification Report - Validation data",end="\n\n")
cr = classification_report(y_val,y_valid_pred>0.5)
print(cr)

print("Classification Report - Test data",end="\n\n")
cr = classification_report(y_test,y_test_pred>0.5)
print(cr)

"""1.   The wighted avg Recall value is 0.98
2.   Recall has 0.98 value & good balance between Precision & f1-scope

# **Actionable Insights and Recommendations**

Write down some insights and business recommendations based on your observations.



1.   ReNeWind company can deploy the final model (model4) -  two hidden layer & activation function - ReLU & Adam optimizer with batch normalization
2.   This model shows the best performance with smallest difference between train & validation data
3.   It helps ReNeWind to detect generator failures before they occur for timely maintenance. It minimize the costly breakdowns & overall maintenance costs.
4.   This model helps to achieve company goal
"""